twitterAnalyzer/sentiment/urls.py
from django.urls import path

from . import views

app_name = 'sentiment'

urlpatterns = [
    path('', views.index, name='index'),
    # /sentiment/detail
    path('hashtag/detail/<str:tag>/', views.detail, name='tag-detail'),
    # /sentiment/results
    #path('search/results/?page=<int:page>', views.results, name='search-results'),
]

twitterAnalyzer/twitterAnalyzer/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('sentiment/', include('sentiment.urls')),
    path('admin/', admin.site.urls),
]

twitterAnalyzer/sentiment/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.

class Tweet(models.Model):
    geo = models.CharField(max_length=6)
    
    hashtag = models.CharField(max_length=280, 
                               null = True)
                               
    tweetkey = models.DecimalField(max_digits = 19, 
                                   decimal_places=0)
                                   
    latitude = models.DecimalField(max_digits = 9, 
                                   decimal_places = 6, 
                                   null = True)
                                   
    longitude = models.DecimalField(max_digits = 9, 
                                    decimal_places = 6, 
                                    null = True)
                                    
    mention = models.CharField(max_length=280, 
                               null = True)
                               
    tweet = models.CharField(max_length=1024)
    
    time_stamp = models.DateTimeField('date posted')
    
    tweeturl = models.CharField(max_length=128)
    
    user_name = models.CharField(max_length = 280)
    
    sentiment = models.DecimalField(max_digits = 1, 
                                    decimal_places = 0)
    
    def __str__(self):
        output = self.geo + "\t" + self.hashtag + "\t" + self.tweet_id\
                          + "\t" + latitude + "\t" + self.longitude\
                          + "\t" + self.mention + "\t" + self.tweet + "\t"\
                          + self.time_stamp + "\t" + self.user_name + "\t"\
                          + self.sentiment
        return output
    

twitterAnalyzer/sentiment/views.py
from django.shortcuts import render # For rendering HTTP requests
from django.http import HttpResponse
from django.http import Http404 # For not found
from django.db.models import Q, Subquery, Count, DecimalField # For running complex queries
from django.db.models.functions import ExtractHour
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
import numpy as np
import matplotlib
import matplotlib.mlab as mlab
import matplotlib.pyplot as plt
import itertools
import array as arr
from .models import Tweet

def index(request):
    tweets = None
    counts = 0
    search = ''
    if request.GET.get('search'):
        search = request.GET.get('search')
        # Search for hashtag or mention like search term
        #tweets_with_hashtags = Tweet.objects.filter(~Q(hashtag='') | ~Q(mention=''))
        tweets = Tweet.objects.filter(Q(hashtag=search) | Q(mention=search))\
                              .values('hashtag', 'mention', 'tweeturl',
                                      'tweet', 'sentiment', 'user_name', 'time_stamp')
        counts = tweets.count()
        # Render the results in the same page
    return render(request, 'sentiment/index.html', {'tweets': tweets,
                                                    'counts':counts, 'search': search})

def detail(request, tag):
    tweets = None
    counts = 0
    # Search for that specific hashtag    
    #tweets = Tweet.objects.filter(Q(hashtag=tag) | Q(mention=tag))\
    #                      .values('hashtag', 'mention', 'tweeturl', 
    #                              'tweet', 'sentiment', 'user_name', 'time_stamp')

    tweets = Tweet.objects.filter(Q(hashtag=tag) | Q(mention=tag))\
              .values(hour=ExtractHour('time_stamp'))\
              .annotate(negative=Count('sentiment',
                        output_field=DecimalField(max_digits=1, decimal_places=0),
                        filter=Q(sentiment='1',)), 
                        positive=Count('sentiment',
                        output_field=DecimalField(max_digits=1, decimal_places=0),
                        filter=Q(sentiment='0',)),
                        count=Count('sentiment',
                        output_field=DecimalField(max_digits=1, decimal_places=0))).order_by('hour')
    
    # Get statistics
    hours = list(range(0,24)) # Get a list of the hours in a day
    pos_hours = {hour: 0 for hour in hours} # Dictionary to store results
    neg_hours = {hour: 0 for hour in hours} # Dictionary to store results
    positive_count = 0
    negative_count = 0
    #count_tweets = {hour: 0 for hour in hours};
    #avg_positive = 0
    #avg_negative = 0
    counts = 0
    pos_cumulative = arr.array('f', [])
    neg_cumulative = arr.array('f', [])
    #tweets_cumulative = arr.array('i', [])
    for record in tweets.iterator():
        positive_count = positive_count + record["positive"]
        pos_hours[record["hour"]] = record["positive"]
        negative_count = negative_count + record["negative"]
        neg_hours[record["hour"]] = record["negative"]
        counts = counts + positive_count + negative_count
        #count_tweets[record["hour"]] = record["count"] 
        pos_cumulative.append(positive_count)
        neg_cumulative.append(negative_count)
        #tweets_cumulative.append(counts)
        #avg_positive[record["hour"]] = (positive_count // counts)
        #avg_negative[record["hour"]] = (negative_count // counts)
    
    #positive_count = tweets.filter(sentiment='0').count()
    #negative_count = tweets.filter(sentiment='1').count()
    positive_percent = positive_count/counts
    negative_percent = negative_count/counts
    
    # Values for y_axis bar graph and pie chart
    y_axis = [positive_count, negative_count]
    
    
    # For use as labels
    x_axis = ['positive', 'negative']
    
    # Get the pie chart
    colors = ['lightskyblue','gold']
    explode= (0.1,0)
    plt.pie(y_axis, explode=explode, labels=x_axis, colors=colors,
            autopct='%1.1f%%', shadow=True, startangle=90)
    plt.title('Positive vs Negative Sentiment Percentage')
    plt.legend('positive','negative')
    plt.axis('equal')
    plt.savefig(r'C:\twitterAnalyzer\Scripts\twitterAnalyzer\sentiment\static\sentiment\sentiment_piechart.png')
    plt.gcf().clear()
    
    # Get the histogram
    plt.bar(x_axis, y_axis, align='center')
    plt.xlabel('Sentiment')
    plt.ylabel('Frequency')
    plt.title('Sentiment Distribution')
    plt.legend('positive','negative')
    plt.savefig(r'C:\twitterAnalyzer\Scripts\twitterAnalyzer\sentiment\static\sentiment\sentiment_hist.png')
    plt.gcf().clear()
    
    number_bins = np.arange(len(hours))
    width = 0.35
    
    fig, ax = plt.subplots()
    
    pos_rect = ax.bar(number_bins, pos_hours.values(), width, color = 'lightskyblue')
    neg_rect = ax.bar(number_bins + width, neg_hours.values(), width, color = 'gold')
    ax.set_xlabel('Hour')
    ax.set_ylabel('Tweet Frequency')
    ax.set_title('Positive vs Negative Sentiment by Hour')
    ax.legend('positive','negative')
    ax.set_xticks(number_bins + width/2)
    ax.set_xticklabels(hours)
    plt.savefig(r'C:\twitterAnalyzer\Scripts\twitterAnalyzer\sentiment\static\sentiment\sentiment_hour.png')
    plt.gcf().clear()

    # Get the double line graph
    x = np.arange(len(hours))

    #plt.gca().set_color_cycle(['blue', 'red'])
    plt.xlabel('Hour');
    plt.ylabel('Tweet Frequency');
    plt.title('Positive vs Negative Sentiment Frequency Over Time (Hours)');

    plt.plot(x, pos_cumulative[:])
    plt.plot(x, neg_cumulative[:])
    #plt.plot(x, tweets_cumulative[:])
    

    plt.legend(['Positive sentiment', 'Negative sentiment'], loc='upper left')

    plt.savefig(r'C:\twitterAnalyzer\Scripts\twitterAnalyzer\sentiment\static\sentiment\double_line_sentiment_hour.png')
    plt.gcf().clear()
    #plt.show()
        
    header = tag
    
    return render(request, 'sentiment/detail.html', {'tweets': tweets,
                                                     'counts': counts,
                                                     'header': header,})
#def results(request, search):
#    return render(request, 'sentiment/results.html', {'search':search})

twitterAnalyzer/sentiment/templates/sentiment/detail.html
{% load static %}
<link href="{% static "sentiment/favicon.ico" %} rel="icon" type="image/x-icon" />
<link rel="stylesheet" type="text/css" href="{% static 'sentiment/style.css' %}">
<header> {{header}} hashtag details: {{counts}} total tweets</header>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<a href ="{% url 'sentiment:index' %}">Return to search</a>
<img src="{% static "sentiment/sentiment_piechart.png" %}" alt = "Histogram">
<img src="{% static "sentiment/sentiment_hist.png" %}" alt = "Histogram">
<img src="{% static "sentiment/sentiment_hour.png" %}" alt = "Histogram by Hour">
<img src="{% static "sentiment/double_line_sentiment_hour.png" %}" alt = "Double Line Graph by Hour">

twitterAnalyzer/sentiment/templates/sentiment/index.html
{% load static %}
{% load sentiment_extras %}
<link href="{% static "sentiment/favicon.ico" %} rel="icon" type="image/x-icon" />
<link rel="stylesheet" type="text/css" href="{% static 'sentiment/style.css' %}">

<header>Welcome to hashtag search</header>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form method="GET">
{% csrf_token %}
<label for="searchterm">Enter the hashtag to search on:</label>
<input type="text" name="search">
</form>
<br/><br/>


<table id="search_results">
    <caption>Search results for {{search}}:  {{counts}} tweets</caption>
    <thead>
        <tr>
        <th>Hashtag</th>
        <th>Mention</th>
        <th>User Name</th>
        <th>Tweet URL</th>
        <th>Tweet Text</th>
        <th>Sentiment</th>
        <th>Time Posted</th>
        </tr>
    </thead>
    <tbody>
        {% for tweet in tweets %}
        <tr>
            <td><a href="{{ "hashtag/detail/"|concatenate:tweet.hashtag}}" target="_blank">{{tweet.hashtag}}</a></td>
            <td><a href ="{{ "hashtag/detail/"|concatenate:tweet.mention }}" target = "_blank">{{tweet.mention}}</a></td>
            <td>{{tweet.user_name}}</td>            
            <td><a href ="{{tweet.tweeturl}}" target = "_blank"</a>{{tweet.tweeturl}}</td>
            <td>{{tweet.tweet}}</td>
            <td>{{tweet.sentiment}}</td>
            <td>{{tweet.time_stamp}}</td>
        </tr>
        {% endfor %}
    </tbody>
    <tfoot>
        <tr>
            <td>End Results</td>
        </tr>
    </tfoot>
</table>

twitterAnalyzer/sentiment/templates/sentiment/results.html
{% load static %}
{% load sentiment_extras %}

<link rel="stylesheet" type="text/css" href="{% static 'sentiment/style.css' %}">

<header>Search results for: {{search}}</header>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<a href ="{% url 'sentiment:index' %}">Return to search</a>

<div class="pagination">
    <span class="step-links">
    
        {% if tweets.has_previous %}
            <a href="search/results/?page=1">&laquo; first</a>            
            <a href="search/reslts/?page={{ tweets.previous_page_number }}">previous"</a>            
        {% endif %}
        
        <span class="current">
            Page {{ tweets.number }} of {{ tweets.paginator.num_pages}}.
        </span>
        
        {% if tweets.has_next %}
            <a href="search/results/?page={{ tweets.next_page_number }}">next</a>            
            <a href="search/results/?page={{ tweets.paginator.num_pages }}">last &raquo;</a>            
        {% endif %}
    
    </span>
</div>    


<table id="search_results">
    <caption>Search Results: {{counts}} Tweets</caption>
    <thead>
        <tr>
        <th>Hashtag</th>
        <th>Mention</th>
        <th>User Name</th>
        <th>Tweet ID</th>
        <th>Tweet Text</th>
        <th>Sentiment</th>
        <th>Time Posted</th>
        </tr>
    </thead>
    <tbody>
        {% for tweet in tweets %}
        <tr>
            <td><a href="{{ "hashtag/detail/"|concatenate:tweet.hashtag}}" target="_blank">{{tweet.hashtag}}</a></td>
            <td><a href ="{{ "hashtag/detail/"|concatenate:tweet.mention }}" target = "_blank">{{tweet.mention}}</a></td>
            <td>{{tweet.user_name}}</td>            
            <td>{{tweet.tweetkey}}</td>
            <td>{{tweet.tweet}}</td>
            <td>{{tweet.sentiment}}</td>
            <td>{{tweet.time_stamp}}</td>
        </tr>
        {% endfor %}
    </tbody>
    <tfoot>
        <tr>
            <td>complete</td>
        </tr>
    </tfoot>
</table>